---
- hosts: database
  handlers:
    - name: "Restart Mysql"
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: "APT Install Mysql"
      apt:
        name:
          - mysql-server
          - mysql-client
          - python3-mysqldb
          - libmysqlclient-dev
        state: present
      become: yes

    - name: "MySQL create database"
      mysql_db:
        name: "{{ wp_db_name }}"
        login_user: root
        state: present

    - name: "MySQL create user"
      mysql_user:
        host: "%"
        login_user: root
        name: "{{ wp_db_user }}"
        password: 12345
        priv: "{{ wp_db_name }}.*:ALL"
        state: present

    - name: "MySQL Config Access"
      copy:
        src: "files/mysqld.cnf"
        dest: "{{ mysql_dir }}/mysqld.cnf"
      become: yes
      notify:
        - Restart Mysql

- hosts: wordpress
  handlers:
    - name: "Restart Apache"
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: "APT Install basic packets PHP and Apache"
      apt:
        name:
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - php
          - libapache2-mod-php
          - php-mysql
          - apache2
        state: present
      become: yes

    - name: "Download latest Wordpress"
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: "Wordpress unarchive"
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: /var/www/
        remote_src: yes
      become: yes

    - name: "Wordpress copy wp-config file"
      copy:
        src: "{{ wp_dir }}/wp-config-sample.php"
        dest: "{{ wp_dir }}/wp-config.php"
        remote_src: yes
      become: yes

    - name: "Wordpress configuring database access in wp-config"
      replace:
        path: "{{ wp_dir }}/wp-config.php"
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: "database_name_here", value: "{{ wp_db_name }}" }
        - { regex: "username_here", value: "{{ wp_db_user }}" }
        - { regex: "password_here", value: "{{ wp_db_passwd }}" }
        - { regex: "localhost", value: "{{ hostvars.database.ansible_host }}" }
      become: yes

    - name: "Wordpress configuring Apache for access"
      template:
        src: "templates/000-default.conf.j2"
        dest: "{{ apache_site_dir }}/000-default.conf"
      become: yes
      notify:
        - Restart Apache
