---
- hosts: all
  tasks:
    - name: "APT Install basic packets"
      apt:
        name:
          - mysql-server
          - mysql-client
          - python3-mysqldb
          - libmysqlclient-dev
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
      become: yes

    - name: "MySQL create database"
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present

    - name: "Mysql create user"
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 12345
        priv: "wordpress_db.*:ALL"
        state: present

    - name: "Download latest Wordpress"
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: "Wordpress unarchive"
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: /var/www/
        remote_src: yes
      become: yes

    - name: "Wordpress copy wp-config file"
      copy:
        src: "/var/www/wordpress/wp-config-sample.php"
        dest: "/var/www/wordpress/wp-config.php"
        remote_src: yes
      become: yes

    - name: "Wordpress configuring database access in wp-config"
      replace:
        path: "/var/www/wordpress/wp-config.php"
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: "database_name_here", value: "wordpress_db" }
        - { regex: "username_here", value: "wordpress_user" }
        - { regex: "password_here", value: "12345" }
      become: yes

    - name: "Wordpress configuring Apache for access wordpress"
      copy:
        src: "files/000-default.conf"
        dest: "/etc/apache2/sites-available/000-default.conf"
      become: yes
