---
- name: "Download latest Wordpress"
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: "Wordpress unarchive"
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: /var/www/
    remote_src: yes
  become: yes

- name: "Wordpress copy wp-config file"
  copy:
    src: "{{ wp_dir }}/wp-config-sample.php"
    dest: "{{ wp_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: "Wordpress configuring database access in wp-config"
  replace:
    path: "{{ wp_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: "database_name_here", value: "{{ wp_db_name }}" }
    - { regex: "username_here", value: "{{ wp_db_user }}" }
    - { regex: "password_here", value: "{{ wp_db_passwd }}" }
    - { regex: "localhost", value: "{{ hostvars.database.ansible_host }}" }
  become: yes

